# Generated by Django 4.2.5 on 2023-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
